name: 'Package and prepare release'
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
jobs:
  build_and_test_apk_testing:
    uses: ./.github/workflows/packagetool.yml
    with:
      package_system: 'apk'
      run_tests: false
      produce_artifact: true
      use_build_cache: true
  # build_and_test_apk:
  #   uses: ./.github/workflows/packagetool.yml
  #   with:
  #     package_system: 'apk'
  #     run_tests: true
  #     produce_artifact: true
  #     use_build_cache: true
  # build_and_test_deb:
  #   uses: ./.github/workflows/packagetool.yml
  #   with:
  #     package_system: 'deb'
  #     run_tests: true
  #     produce_artifact: true
  #     use_build_cache: true
  # build_and_test_rpm:
  #   uses: ./.github/workflows/packagetool.yml
  #   with:
  #     package_system: 'rpm'
  #     run_tests: true
  #     produce_artifact: true
  #     use_build_cache: true
  prepare_release:
    needs:
      - build_and_test_apk_testing
      # - build_and_test_apk
      # - build_and_test_deb
      # - build_and_test_rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts
      - name: Create tarballs & get timestamp
        id: tarball_and_timestamp
        run: |
          mkdir -p /tmp/tarballs
          for artifact_dir in /tmp/artifacts/*; do
            artifact_name="${artifact_dir##*/}"
            tar -C "$artifact_dir" -czf "/tmp/tarballs/$artifact_name.tar.gz" .
          done
          printf 'RELEASE_TIMESTAMP=\'%s\'' "$(date -u '+%Y-%m-%d %H:%M:%S')" | tee -a "$GITHUB_OUTPUT"
      - name: Create release draft
        uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
        with:
          name: ${{ steps.tarball_and_timestamp.outputs.RELEASE_TIMESTAMP }}
          draft: true
          prerelease: true
          files: /tmp/tarballs/*