name: Package module for Alpine Linux

on: workflow_dispatch
jobs:
  packagetool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current week of the year
        id: current_week_number
        run: printf 'WEEK_NUMBER=%s' "$(date +%V)" | tee -a "$GITHUB_OUTPUT"
      - name: Get Podman user var directory
        id: podman_user_var_dir
        run: printf 'PODMAN_USER_VAR_DIR=%s' "$(podman info --format '{{.Store.GraphRoot}}' | sed 's|/[^/]*$|/|')" | tee -a "$GITHUB_OUTPUT"
      - name: Podman Cache ${{ steps.podman_user_var_dir.outputs.PODMAN_USER_VAR_DIR }}
        uses: actions/cache@v3
        with:
          path: ${{ steps.podman_user_var_dir.outputs.PODMAN_USER_VAR_DIR }}
          key: containers-${{ steps.current_week_number.outputs.WEEK_NUMBER }}
      - name: Run packagetool.sh
        run: ./packagetool.sh --container_runtime=podman --package_system=apk --print_temp_dir=normal
      - name: Upload .release folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-folder
          path: ./.release