name: Test packaging and dynamic building of the module
on: workflow_dispatch
env:
  DOCKER_CACHE_DIR: /tmp/GitHubActions-DockerCache
jobs:
  apk:
    runs-on: ubuntu-latest
    env:
      PACKAGE_SYSTEM: apk
      DOCKER_CACHE_DIR: /tmp/GitHubActions-DockerCache-apk
    steps:
      - uses: actions/checkout@v3
      - name: Set up job environment
        id: jobenv
        run: |
          printf 'CACHE_YEAR_AND_WEEK=%s\n' "$(date +Y%YW%V)" | tee -a "$GITHUB_OUTPUT"
          mkdir -p "${{ env.DOCKER_CACHE_DIR }}""
          docker buildx create --use --driver=docker-container
      - name: GitHub Actions Cache for Docker
        uses: actions/cache@v3
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}
          key: docker-cache-${{ env.PACKAGE_SYSTEM }}-${{ steps.jobenv.outputs.CACHE_YEAR_AND_WEEK }}
      - name: Run packagetool.sh
        run: |
          ./packagetool.sh \
            --container_runtime=docker \
            --package_system=${{ env.PACKAGE_SYSTEM }} \
            --print_temp_dir=normal \
            --container_security_privileged \
            --keep_temp_dir \
            --local_cache_dir="${{ env.DOCKER_CACHE_DIR }}"
      - name: Upload .release folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ env.PACKAGE_SYSTEM }}
          path: ./.release