name: Test module for Debian & Derivatives/dkms

on: workflow_dispatch
jobs:
  packagetool:
    env:
      DOCKER_CACHE_DIR: /tmp/gh_actions-docker_cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up job environment
        id: jobenv
        run: |
          sudo su
          docker buildx create --use --driver=docker-container
          mkdir -p "${{ env.DOCKER_CACHE_DIR }}"
          printf 'CACHE_YEAR_AND_WEEK=%s\n' "$(date +Y%YW%V)" | tee -a "$GITHUB_OUTPUT"
      - name: GitHub Actions Cache for Docker
        uses: actions/cache@v3
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}
          key: docker-cache-deb-${{ steps.jobenv.outputs.CACHE_YEAR_AND_WEEK }}
      - name: Run packagetool.sh
        run: ./packagetool.sh --container_runtime=docker --package_system=deb --print_temp_dir=normal --container_security_privileged --keep_temp_dir --local_cache_dir="${{ env.DOCKER_CACHE_DIR }}"
      - name: Upload .release folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-folder
          path: ./.release