name: Test packaging and dynamic building of the module
on: workflow_dispatch
env:
  DOCKER_CACHE_DIR: /tmp/GitHubActions-DockerCache
  STD_ENV_COMMAND: |
    docker buildx create --use --driver=docker-container
    echo "123"
    printf 'CACHE_YEAR_AND_WEEK=%s\n' "$(date +Y%YW%V)" | tee -a "$GITHUB_OUTPUT"
    echo 456
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "TESTING"
        run: |
          ${{ env.STD_ENV_COMMAND }} --test